name: Solar System Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      #- main
      - 'feature/*'
env:
    MONGO_URI: ${{ vars.MONGO_URL }}
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
jobs:
    unit-testing:
        name: Unit Testing
        strategy:
          matrix:
            node-version: [18, 19, 20]
            os: [ubuntu-latest, macos-latest]
            exclude:
              - node-version: 18
                os: macos-latest
        runs-on: ${{ matrix.os }}
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v3

        - name: Setup NodeJS Version - ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
    
        - name: Install Dependencies
          run: npm install
    
        - name: Unit Testing
          run: npm test
          
        - name: Archive Test Result
          uses: actions/upload-artifact@v4
          with:
            name: Mocha-Test-${{ matrix.node-version }}-${{ matrix.os }}
            path: test-results.xml

    code-coverage:
        name: Code Coverage
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v3

        - name: Setup NodeJS Version
          uses: actions/setup-node@v3
          with:
            node-version: 18
    
        - name: Install Dependencies
          run: npm install

        - name: check Code Coverage
          run: npm run coverage
          continue-on-error: true
    
        - name: Archive Coverage Result
          uses: actions/upload-artifact@v4
          with:
            name: Coverage-Report
            path: coverage-results
            retention-days: 5
